[package]
name = "ic-certification"
version = "0.1.3"
description = "Certification and Canister Signatures"
repository = "https://github.com/nomeata/ic-certification"

[dependencies]
sha2 = "0.1.4"
cbor = "2.0.0"

[dev-dependencies]
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[toolchain]
moc = "0.14.13"
